import assert from 'node:assert/strict';
import { test } from 'node:test';
import { DEFAULT_API_URL, normalizeApiUrl, renderApiConfig } from './generate-api-config.mjs';

test('uses the local API by default', () => {
  assert.equal(normalizeApiUrl(undefined), DEFAULT_API_URL);
  assert.equal(normalizeApiUrl('  '), 'http://localhost:3003/api');
});

test('keeps the /api base and drops the trailing slash', () => {
  assert.equal(normalizeApiUrl('https://api-wtw.example.com/api/'), 'https://api-wtw.example.com/api');
  assert.equal(normalizeApiUrl('/api'), '/api');
});

test('rejects values that are not http(s) URLs or paths', () => {
  assert.throws(() => normalizeApiUrl('ftp://example.com/api'));
  assert.throws(() => normalizeApiUrl('api.example.com'));
});

test('renders a TypeScript constant', () => {
  assert.equal(
    renderApiConfig('https://api-wtw.example.com/api'),
    '// Generated by scripts/generate-api-config.mjs; do not edit.\nexport const API_URL = "https://api-wtw.example.com/api";\n'
  );
});
